version: '3.8'

services:
  postgres_sweep:
    image: postgres:16-alpine
    container_name: postgres_sweep
    environment:
      POSTGRES_DB: sweepdb
      POSTGRES_USER: sweepuser
      POSTGRES_PASSWORD: sweeppass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - sweep-network

  server:
    build:
      context: ..
      dockerfile: Sweep-Server/Dockerfile
    container_name: sweep_server
    depends_on:
      - postgres_sweep
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_sweep:5432/sweepdb
      SPRING_DATASOURCE_USERNAME: sweepuser
      SPRING_DATASOURCE_PASSWORD: sweeppass
    ports:
      - "8080:8080"
    networks:
      - sweep-network

volumes:
  postgres_data:


networks:
  sweep-network:
    driver: bridge
